name: qsrr_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - bleach=4.1.0
  - boost=1.78.0
  - boost-cpp=1.78.0
  - bottleneck=1.3.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=38.0.2
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.13.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.84.3
  - glib-tools=2.84.3
  - greenlet=1.1.3
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.2.0
  - intel-openmp=2024.2.1
  - ipykernel=6.15.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.4.4
  - jupyter_core=4.11.2
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libdeflate=1.14
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.84.3
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libogg=1.3.5
  - libpng=1.6.50
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxml2=2.13.8
  - libxslt=1.1.41
  - libzlib=1.3.1
  - lxml=4.9.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2024.2.2
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.7.3
  - numpy=1.21.6
  - openjpeg=2.5.0
  - openssl=3.5.2
  - packaging=23.2
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.45
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - pixman=0.46.4
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pycairo=1.21.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.1.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.16.2
  - python_abi=3.7
  - pytz=2024.2
  - pywin32=305
  - pywinpty=2.0.10
  - pyzmq=23.2.0
  - qt-main=5.15.8
  - qt-webengine=5.15.9
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - qtwebkit=5.212
  - rdkit=2022.09.1
  - reportlab=3.5.68
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.42
  - sqlite=3.50.2
  - tbb=2021.13.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - ucrt=10.0.22621.0
  - unicodedata2=14.0.0
  - urllib3=1.26.14
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.3.1
  - zstd=1.5.7
